version: '3.9'
services:
  db:
    image: mongo:4.4-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  php:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        ENABLE_PHP_XDEBUG: 1
    ports:
      - '9000:9001'
    volumes:
      - ./application:/var/www/application
      - ./logs/application:/var/www/application/var/log
    depends_on:
      - db
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./application:/var/www/application
